### ISSUE TITLE
Update for recent cinnamon versions?

### ISSUE THREAD

**Issue by kr428** [zagortenay333/timepp__cinnamon#1]
Is it possible to have an update for current cinnamon? :)

**Comment by zagortenay333** [comment]
Does it now work?

The thing is that the gnome-shell version has a huge number of updates compared to the cinna version.
At some point I will simply port the entire gnome-shell version in one swoop rather than incrementally updating.

**Comment by kr428** [comment]
Nope, unfortunately it doesn't. Right now this is what I see here:

`error t=2017-11-06T07:32:55.532Z No JS module 'applet' found in search path
trace t=2017-11-06T07:32:55.532Z 
<----------------
@/home/kr/.local/share/cinnamon/applets/timepp@zagortenay333/applet.js:10:7
Extension.prototype._init@/usr/share/cinnamon/js/ui/extension.js:156:13
Extension@/usr/share/cinnamon/js/ui/extension.js:115:5
loadExtension@/usr/share/cinnamon/js/ui/extension.js:450:25
init@/usr/share/cinnamon/js/ui/appletManager.js:47:9
start@/usr/share/cinnamon/js/ui/main.js:493:5
@<main>:1:31
---------------->
error t=2017-11-06T07:32:55.533Z [Applet "timepp@zagortenay333"]: Error importing applet.js from timepp@zagortenay333
error t=2017-11-06T07:32:55.533Z Could not load applet timepp@zagortenay333`

This is cinnamon 3.6.0 on Arch. Unfortunately I don't yet know enough about how these applets work internally to be of any help debugging this any deeper...

**Comment by zagortenay333** [comment]
Yeah, I won't be updating this in a while. Like I said, when I do I'll port the entire gnome-shell version over.

**Comment by kr428** [comment]
No hurry - thanks for looking into it at all. :)

**Comment by 9R** [comment]
@kr428: I ran into the same problem and i fixed the failing imports for 3.6. Until the gnome-shell version is ported you can use the fixed version from #3
