### ISSUE TITLE
Cannot put number from keyboard to the number selectors.

### ISSUE THREAD

**Issue by emrsmsrli** [zagortenay333/timepp__cinnamon#2]
Hi, 

I cannot enter a number from the keyboard to the number input fields. Only up and down arrows work. I'm using Ubuntu 17.04, also tried on 16.04. I have a custom theme if it helps, [Materia](https://github.com/nana-4/materia-theme).
Also, here are two screenshots attached. 

![screenshot from 2017-12-26 00-03-21](https://user-images.githubusercontent.com/16121887/34342925-a92f04fc-e9d0-11e7-9343-ad7c02ef2c2e.png)

![screenshot from 2017-12-26 00-03-13](https://user-images.githubusercontent.com/16121887/34342924-a7e64b50-e9d0-11e7-966c-df1703143607.png)

**Comment by zagortenay333** [comment]
That's because that is not an input field.

**Comment by emrsmsrli** [comment]
You should consider making it an input field, then. It's inconvenient the way it is now. Thanks for the answer, though.

**Comment by zagortenay333** [comment]
Yeah it could be a faster input if you could type, but then I would need to do more input checking which is not worth it.
